# Generated by Django 4.2.2 on 2025-05-13 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_project_image_projectimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='download_file',
            field=models.FileField(blank=True, null=True, upload_to='media/project_files/'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(upload_to='media/project_images/'),
        ),
    ]
