# Generated by Django 5.2.1 on 2025-06-03 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_profile_unique_together_profile_projects_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='projects',
        ),
    ]
