# Generated by Django 5.2.1 on 2025-06-11 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_requestlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestlog',
            name='device_type',
        ),
        migrations.AddField(
            model_name='requestlog',
            name='device_info',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
