# Generated by Django 5.2.1 on 2025-06-12 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_remove_requestlog_device_type_requestlog_device_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='experience_years',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
