# Generated by Django 5.2.1 on 2025-06-14 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_profile_experience_years'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlog',
            name='referer',
            field=models.URLField(blank=True, null=True),
        ),
    ]
