# Generated by Django 5.2.3 on 2025-11-10 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_requestlog_referer'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlog',
            name='ip_addresses',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
