name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH into AWS and deploy Docker container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            cd /home/ubuntu/apps/Portfolio-Backend

            # Pull latest Docker image from Docker Hub
            sudo docker pull shudipta0301/portfolio:latest

            # Stop and remove the old container if running
            sudo docker stop portfolio-container || true
            sudo docker rm portfolio-container || true

            # Run database migrations using a temporary container
            sudo docker run --rm \
              -v /home/ubuntu/apps/Portfolio-Backend/media/:/app/media/ \
              --env-file /home/ubuntu/apps/Portfolio-Backend/.env.production \
              shudipta0301/portfolio:latest \
              python manage.py migrate --noinput

            # Run the new Docker container  
            sudo docker run -d \
              --name portfolio-container \
              -p 8001:8000 \
              -v /home/ubuntu/apps/Portfolio-Backend/media/:/app/media/ \
              --env-file /home/ubuntu/apps/Portfolio-Backend/.env.production \
              shudipta0301/portfolio:latest